---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# fixie_teeth
Fixie builders frequently face the problem to choose a gear ratio (i.e. the number of chainring teeth divided by the number of cogring teeth) that provides them with as many skid patches as possible.

For instance, choosing 40 teeth for the chainring and 20 teeth for the cogring, is one of the worst possible combinations since it gives you only a single skid patch (a skid patch is a point on the tire rapidly wearing off due to skid stop braking). Naturally, it is much better for the longevity of your tire to choose a teeth combination resulting in as many skid patches as possible.

This App does exactly that. It calculates the optimal chain- and cogring teeth combination for a given gear ratio within a specified gear ratio tolerance range (default: desired gear ratio +/- 0.1). The result is a table with a chain- and cogring teeth combination sorted descendingly first by the number of skid patches and secondly by the desired gear ratio.

